In [21]:
numpynumpy.

67


In [30]:
a = np.array([1,2,3,4,5])

In [32]:
a.max()

5

In [38]:
a=np.array([1,2,3,4,5,6])

In [53]:
a[1:6]

array([2, 3, 4, 5, 6])

In [69]:
a = np.array([1,2,3,5,6])

In [72]:
a[1:3]=111

In [73]:
a

array([  1, 111, 111,   5,   6])

In [74]:
a[3]=1111

In [75]:
a

array([   1,  111,  111, 1111,    6])

In [94]:
c = a.copy()

In [95]:
c

array([   1,  111,  111, 1111,    6])

In [96]:
c[0] = 0

In [97]:
c


array([   0,  111,  111, 1111,    6])

In [98]:
a

array([   1,  111,  111, 1111,    6])

In [10]:
#importing files
import pandas as pd
df= pd.read_csv('C:\\Users\\anil\\Desktop\\STUDY AREA\\PYTHON FOR DATA SCIENCE
\\DemographicData.csv',sep=',')

SyntaxError: EOL while scanning string literal (<ipython-input-10-48773097e1c2>, line 3)

In [3]:
import os

In [5]:
print(os.getcwd())

C:\Users\anil\Desktop\STUDY AREA\PYTHON FOR DATA SCIENCE


In [15]:
os.chdir('C:\\Users\\anil\\Desktop\\STUDY AREA\\PYTHON FOR DATA SCIENCE')

In [18]:
df = pd.read_csv("DemographicData.csv")
df

Country Name Country Code  Birth rate  Internet users  \
0                   Aruba          ABW      10.244            78.9   
1             Afghanistan          AFG      35.253             5.9   
2                  Angola          AGO      45.985            19.1   
3                 Albania          ALB      12.877            57.2   
4    United Arab Emirates          ARE      11.044            88.0   
..                    ...          ...         ...             ...   
190           Yemen, Rep.          YEM      32.947            20.0   
191          South Africa          ZAF      20.850            46.5   
192      Congo, Dem. Rep.          COD      42.394             2.2   
193                Zambia          ZMB      40.471            15.4   
194              Zimbabwe          ZWE      35.715            18.5   

            Income Group  
0            High income  
1             Low income  
2    Upper middle income  
3    Upper middle income  
4            High income  
..                   ...  
190  Lower middle income  
191  Upper middle income  
192           Low income  
193  Lower middle income  
194           Low income  

[195 rows x 5 columns]

In [27]:
import pandas as pd
df = pd.read_csv("C:\\Users\\anil\\Desktop\\STUDY AREA\\PYTHON FOR DATA SCIENCE\\DemographicData.csv")

In [28]:
df

Country Name Country Code  Birth rate  Internet users  \
0                   Aruba          ABW      10.244            78.9   
1             Afghanistan          AFG      35.253             5.9   
2                  Angola          AGO      45.985            19.1   
3                 Albania          ALB      12.877            57.2   
4    United Arab Emirates          ARE      11.044            88.0   
..                    ...          ...         ...             ...   
190           Yemen, Rep.          YEM      32.947            20.0   
191          South Africa          ZAF      20.850            46.5   
192      Congo, Dem. Rep.          COD      42.394             2.2   
193                Zambia          ZMB      40.471            15.4   
194              Zimbabwe          ZWE      35.715            18.5   

            Income Group  
0            High income  
1             Low income  
2    Upper middle income  
3    Upper middle income  
4            High income  
..                   ...  
190  Lower middle income  
191  Upper middle income  
192           Low income  
193  Lower middle income  
194           Low income  

[195 rows x 5 columns]

In [30]:
import pandas as pd
df6 = pd.read_csv("C:\\Users\\anil\\Desktop\\STUDY AREA\\PYTHON FOR DATA SCIENCE\\movieratings.csv")

In [31]:
df6

Film      Genre  Rotten Tomatoes Ratings %  \
0    (500) Days of Summer      Comedy                         87   
1              10,000 B.C.  Adventure                          9   
2               12 Rounds      Action                         30   
3                127 Hours  Adventure                         93   
4                17 Again      Comedy                         55   
..                     ...        ...                        ...   
554          Your Highness     Comedy                         26   
555        Youth in Revolt     Comedy                         68   
556                 Zodiac   Thriller                         89   
557            Zombieland      Action                         90   
558              Zookeeper     Comedy                         14   

     Audience Ratings %  Budget (million $)  Year of release  
0                    81                   8             2009  
1                    44                 105             2008  
2                    52                  20             2009  
3                    84                  18             2010  
4                    70                  20             2009  
..                  ...                 ...              ...  
554                  36                  50             2011  
555                  52                  18             2009  
556                  73                  65             2007  
557                  87                  24             2009  
558                  42                  80             2011  

[559 rows x 6 columns]